# baseURL
@baseURL = http://localhost:3009

###
# User Signup
POST http://localhost:3009/signup
Content-Type: application/json

{
    "email": "exampl2e@email.com",
    "password": "password",
    "name": "Vasya",
    "avatar": "Test"
}

###
# User Login
POST http://localhost:3009/login
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# User Logout
POST http://localhost:3009/logout
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}
