# baseURL
# baseURL = http://localhost:3009


###
# Find All Users
GET http://localhost:3000/users

### Find All Users heroku
# GET https://back-social.herokuapp.com/users

###
# Find User By Id
GET http://localhost:3009/users/1


###
# Modify User By Id
PUT http://localhost:3009/users/1
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Delete User By Id
DELETE http://localhost:3009/users/1
